from stable_baselines3.common.vec_env import VecEnvWrapper
from stable_baselines3.common.vec_env.stacked_observations import StackedObservations
from gymnasium import spaces

import gym
import numpy as np

class MovingAverage(object):
  """Computes the moving average of a variable."""

  def __init__(self, capacity):
    self._capacity = capacity
    self._history = np.array([0.0] * capacity)
    self._size = 0

  def add(self, value):
    index = self._size % self._capacity
    self._history[index] = value
    self._size += 1

  def mean(self):
    if not self._size:
      return None
    if self._size < self._capacity:
      return np.mean(self._history[0:self._size])
    return np.mean(self._history)
  
class ICMCuriosityEnvWrapper(VecEnvWrapper):
  """Environment wrapper that adds additional curiosity reward."""

  def __init__(self,
               vec_env,
               world_model,
               add_stoch = False,
               exploration_reward = 'intrinsic_curiosity',
               scale_task_reward = 1.0,
               scale_surrogate_reward = 0.5,
               bonus_reward_additive_term = 0,
               exploration_reward_min_step = 5000):
    
    assert isinstance(
        vec_env.observation_space, (spaces.Box, spaces.Dict)
    ), "Frame Stacking only works with gym.spaces.Box and gym.spaces.Dict observation spaces"

    #self.stacked_obs = StackedObservations(vec_env.num_envs, n_stack, vec_env.observation_space, channels_order)
    #stacked_observation_space = self.stacked_obs.stacked_observation_space
    VecEnvWrapper.__init__(self, venv=vec_env, observation_space=vec_env.observation_space)#stacked_observation_space)

    # obs from env are now of shape (n_envs, original_shape * n_stack)
    self.add_stoch = add_stoch
    self._bonus_reward_additive_term = bonus_reward_additive_term
    self.world_model = world_model

    self._exploration_reward = exploration_reward
    self._scale_task_reward = scale_task_reward
    self._scale_surrogate_reward = scale_surrogate_reward
    self._exploration_reward_min_step = exploration_reward_min_step

    # Cumulative task reward over an episode.
    self._episode_task_reward = [0.0] * self.venv.num_envs
    self._episode_bonus_reward = [0.0] * self.venv.num_envs
    self._episode_uncertainty_reward = [0.0] * self.venv.num_envs

    # Stats on the task and exploration reward.
    self._stats_task_reward = MovingAverage(capacity=100)
    self._stats_bonus_reward = MovingAverage(capacity=100)
    self._stats_uncertainty_reward = MovingAverage(capacity=100)

    # Total number of steps so far per environment.
    self._step_count = 0

    # Observers are notified each time a new time step is generated by the
    # environment.
    # Observers implement a function "on_new_observation".
    self._observers = []
    
  def add_observer(self, observer):
    self._observers.append(observer)

  def _compute_intrinsic_reward(self, obs, actions, next_obs, dones, infos):
    #for i in range(len(next_obs['pixels'])): print('wrapper level',next_obs['pixels'][i].shape, obs['pixels'][i].shape) 
    #print(self.observation_space)
    
    # Update the Observers
    for observer in self._observers:
      observer.on_new_observation(obs, actions, next_obs, rewards, dones, infos)

    if self._exploration_reward == 'intrinsic_curiosity':
      feature_rewards, uncertainty_rewards = self.world_model.reward(obs, actions, next_obs)
      b_rewards = np.zeros(self.venv.num_envs)
      u_rewards = np.zeros(self.venv.num_envs)
      for k in range(self.venv.num_envs):
        b_rewards[k] = feature_rewards[k]
        u_rewards[k] = uncertainty_rewards[k]

      bonus_rewards = [
          0.0 if d else 0.5 + s + u + self._bonus_reward_additive_term
          for (s, u, d) in zip(b_rewards, u_rewards, dones)
      ]

      bonus_rewards = np.array(bonus_rewards)
      
    elif self._exploration_reward == 'none':
      bonus_rewards = np.zeros(self.venv.num_envs)
    else:
      raise ValueError('Unknown exploration reward: {}'.format(
          self._exploration_reward))

    # Combined rewards.
    scale_surrogate_reward = self._scale_surrogate_reward
    if self._step_count < self._exploration_reward_min_step:
      # This can be used for online training during the first N steps,
      # the ICM is totally random and the surrogate reward has no
      # meaning.
      scale_surrogate_reward = 0.0

    postprocessed_rewards = (self._scale_task_reward * rewards +
                             scale_surrogate_reward * bonus_rewards)

    # Update the statistics.
    for i in range(self.venv.num_envs):
      self._episode_task_reward[i] += rewards[i]
      self._episode_bonus_reward[i] += bonus_rewards[i]
      self._episode_uncertainty_reward[i] += u_rewards[i]
      if dones[i]:
        self._stats_task_reward.add(self._episode_task_reward[i])
        self._stats_bonus_reward.add(self._episode_bonus_reward[i])
        self._stats_uncertainty_reward.add(self._episode_uncertainty_reward[i])
        self._episode_task_reward[i] = 0.0
        self._episode_bonus_reward[i] = 0.0
        self._episode_uncertainty_reward[i] = 0.0

    postprocessed_rewards = np.array(postprocessed_rewards)
    return postprocessed_rewards

  def step_wait(self):
    """Overrides VecEnvWrapper.step_wait."""
    observations, rewards, dones, infos = self.venv.step_wait()
    if self.add_stoch:
      observations = np.clip(observations + np.random.randint(low=-10, high=10, size=observations.shape), 0, 255, out=observations)

    self._step_count += 1

    if (self._step_count % 1000) == 0:
      print('step={} task_reward={} bonus_reward={} scale_bonus={}'.format(
          self._step_count,
          self._stats_task_reward.mean(),
          self._stats_bonus_reward.mean(),
          self._scale_surrogate_reward))

    
    for i in range(self.venv.num_envs):
      infos[i]['task_reward'] = rewards[i]
      for key in observations.keys():
        infos[i][f'task_observation_{key}'] = observations[key][i]

    #observations, infos = self.stacked_obs.update(observations, dones, infos)  # type: ignore[arg-type]
    return observations, rewards, dones, infos

  def reset(self):
    """Overrides VecEnvWrapper.reset."""
    observations = self.venv.reset()
    #observations = self.stacked_obs.reset(observations)  # type: ignore[arg-type]
    return observations
  